FCA_DJANGO/FCA_DJANGO/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('contact/', include('contact.urls')),
    path('apply/', include('apply.urls')),
    path('courses/', include('courses.urls', namespace = 'courses')),
    path('about/', include('about.urls')),
    path('catigory/', include('catigories.urls')),
    path('certificate/', include('certificate.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root =settings.STATIC_ROOT)

FCA_DJANGO/courses/urls.py
from django.contrib import admin
from django.urls import path
from .views import course, courses_list, enroll

app_name = 'courses'

urlpatterns = [
    path('<str:id>/enroll/', enroll , name = 'enroll'),
    path('<str:id>', course, name = 'course_detail'),
    path('', courses_list),
    
]

FCA_DJANGO/home/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.home),
]

FCA_DJANGO/courses/models.py
from django.db import models
from django.utils.text import slugify
class Course(models.Model):
    title = models.CharField(max_length = 50)
    description = models.TextField(max_length = 650)
    price = models.IntegerField(default = 999)
    students_numbe = models.IntegerField()
    course_hours = models.FloatField()
    instructor_name = models.CharField(max_length=50)
    img = models.ImageField(upload_to='courses/images/')
    category = models.ForeignKey('category', on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, null=True, allow_unicode=True )
    
    
    
    
    
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Course, self).save(*args, **kwargs)

    
    def __str__(self):
        return self.title
    
    
class category(models.Model):
    name = models.CharField( max_length = 50)
    
    def __str__(self):
        return self.name
    
    
    
class enrolling(models.Model):
    name = models.CharField( max_length=50)
    phone = models.CharField( max_length=50)
    email = models.EmailField(max_length=254)
    age = models.IntegerField()
    address = models.CharField(max_length=200)
    course = models.ForeignKey('Course', on_delete=models.CASCADE, auto_created= True)
    
    def __str__(self):
        return self.name + ' - '  +  self.phone

FCA_DJANGO/courses/forms.py
from django.forms import ModelForm, TextInput, EmailInput, Select, NumberInput
from .models import enrolling

class Enroll(ModelForm):
    class Meta:
        model = enrolling
        fields = ['name', 'phone', 'email', 'address', 'age']
        widgets = {
            'name': TextInput(attrs={'class' : 'form-control', 'placeholder' : "FIRST NAME" , 'id' : "name" , 'style' : 'width: 100%; height:35px;'}),
            'phone' : TextInput(attrs={'class': 'form-control',  'placeholder' : "PHONE NUMBER" ,  'id' : "" , 'style' : 'width: 100%;height:35px;'}),
            'email' : EmailInput(attrs={'class': 'form-control',  'placeholder' : "E-MAIL" , 'id' : "email" , 'style' : 'width: 100%;height:35px;'}),
            'address' : TextInput(attrs={'class': 'form-control',  'placeholder' : "SUBJECT", 'id' : "subject" , 'style' : 'width: 100%;height:35px;'}),
            'age' : NumberInput(attrs={'class': 'form-control',  'placeholder' : "Your Age", 'id' : "age" , 'style' : 'width: 100%;height:35px;'}),
        }

FCA_DJANGO/courses/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from .models import Course
from .forms import Enroll

def courses_list(request):
    all_courses = Course.objects.all()
    paginator = Paginator(all_courses, 2)
    page_number = request.GET.get('page')
    page_object = paginator.get_page(page_number)
    context = {
        'courses' : page_object
    }
    
    return render(request, 'display_courses.html', context)


def course(request, id):
    global course_details
    course_details = Course.objects.get(id=id)
    context = {
        'course' : course_details,
    }
    return render(request, 'course_details.html', context)


def enroll(request, id):
    course_details = Course.objects.get(id=id)
    if request.method == 'POST':
        form = Enroll(request.POST)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.course = course_details
            myform.save()
            return render(request, 'succ.html')
    else:
        form = Enroll

    context = {
        'form' : form,
        'course' : course_details,
        }
    return render(request, 'enroll_page.html', context)

def course_id():
    course_details = Course.objects.get(id=id)

FCA_DJANGO/courses/templates/course_details.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
  <!-- Navbar Start -->
  <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
    <a href="/" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
        <h2 class="m-0 text-secondary"><img src="{% static 'img/logo.png'%}" alt="FCA" style="width:50px;">&nbsp;</i>French Canadian Academy </h2>
    </a>
    <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto p-4 p-lg-0">
            <a href="/" class="nav-item nav-link">Home</a>
            <a href="/about/" class="nav-item nav-link">About</a>
            <a href="/courses/" class="nav-item nav-link active">Courses</a>
            {% comment %} <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                <div class="dropdown-menu fade-down m-0">
                    <a href="team.html" class="dropdown-item">Our Team</a>
                    <a href="testimonial.html" class="dropdown-item">Testimonial</a>
                    <a href="404.html" class="dropdown-item">404 Page</a>
                </div>
            </div> {% endcomment %}
            <a href="/contact/" class="nav-item nav-link">Contact</a>
            <a href="/certificate/" class="nav-item nav-link">Certificate</a>
        </div>
        {% comment %} <a href="" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block">Join Now<i class="fa fa-arrow-right ms-3"></i></a> {% endcomment %}
    </div>
</nav>
<!-- Navbar End -->

<div class="container mt-5">
<div class="row">
    <div class="col-md-16 offset-md-0">
        <div class="card mb-4 shadow-sm">
            <img src=" {{ course.img.url }}" class="card-img-top" alt="{{ course.title }}">
            <div class="card-body">
                <div class="card-header" >
                    <h4 class=" text-center text-primary px-3">{{ course.title }}</h4>
                </div>
                <h2 class="card-title">{{ course.title }}</h2>
                <p class="card-text" style="font-size: 18px; font-weight: bold;">{{ course.description }}</p>
                <p class="card-text"><span class = "text-primary" ><i class="bi bi-tag-fill text-primary me-2"></i><b>Category:</b> </span> {{ course.category.name }}</p>
                <p class="card-text"><span class = "text-primary" ><i class="fa fa-clock text-primary me-2"></i><b>Course Hours:</b> </span> {{ course.course_hours }}</p>
                <p class="card-text"><span class = "text-primary" ><i class="fa fa-user-tie text-primary me-2"></i><b>Instructor:</b> </span> {{ course.instructor_name }}</p>
                <div class="rating">
                <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star"></span>
                    <span class="review-count">(10 reviews)</span>
                </div>  
                <hr>
                <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'courses:enroll' course.id %}" ><button type="button" class="btn btn-primary" style = "width:20vb; height: 5vb;">Enroll Now</button></a>
                    <!-- You can add more buttons here -->
                </div>
                </div>  
            </div>
            </div>  
        </div>
    </div>
</div>
{% endblock %}

FCA_DJANGO/courses/templates/display_courses.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<!-- Navbar Start -->
<nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
    <a href="/" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
        <h2 class="m-0 text-secondary"><img src="{% static 'img/logo.png'%}" alt="FCA" style="width:50px;">&nbsp;</i>French Canadian Academy </h2>
    </a>
    <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto p-4 p-lg-0">
            <a href="/" class="nav-item nav-link">Home</a>
            <a href="/about/" class="nav-item nav-link">About</a>
            <a href="/courses/" class="nav-item nav-link active">Courses</a>
            {% comment %} <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                <div class="dropdown-menu fade-down m-0">
                    <a href="team.html" class="dropdown-item">Our Team</a>
                    <a href="testimonial.html" class="dropdown-item">Testimonial</a>
                    <a href="404.html" class="dropdown-item">404 Page</a>
                </div>
            </div> {% endcomment %}
            <a href="/contact/" class="nav-item nav-link">Contact</a>
            <a href="/certificate/" class="nav-item nav-link">Certificate</a>
        </div>
        {% comment %} <a href="" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block">Join Now<i class="fa fa-arrow-right ms-3"></i></a> {% endcomment %}
    </div>
</nav>
<!-- Navbar End -->
    <div class="container mt-5">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h6 class="section-title bg-white text-center text-primary px-3">Courses</h6>
            <div class="row g-4 justify-content-center">
                {% for course in courses %}
                    <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                        <div class="course-item bg-light">
                            <div class="position-relative overflow-hidden">
                                <img class="img-fluid" src="{{ course.img.url }}" alt="{{ course.title }}">
                                <div class="w-100 d-flex justify-content-center position-absolute bottom-0 start-0 mb-4">
                                    <a href="{% url 'courses:course_detail' course.id %}" class="flex-shrink-0 btn btn-sm btn-primary px-3 border-end" style="border-radius: 30px 0 0 30px;">Read More</a>
                                    <a href="{% url 'courses:enroll' course.id %}" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 0 30px 30px 0;">Join Now</a>
                                </div>
                            </div>
                            <div class="text-center p-4 pb-0">
                                <h3 class="mb-0">${{ course.price }}</h3>
                                <div class="mb-3">
                                    <small class="fa fa-star text-primary"></small>
                                    <small class="fa fa-star text-primary"></small>
                                    <small class="fa fa-star text-primary"></small>
                                    <small class="fa fa-star text-primary"></small>
                                    <small class="fa fa-star text-primary"></small>
                                    <small>(38)</small>
                                </div>
                                <h5 class="mb-4">{{ course.title }}</h5>
                            </div>
                            <div class="d-flex border-top">
                                <small class="flex-fill text-center border-end py-2"><i class="fa fa-user-tie text-primary me-2"></i>{{ course.instructor_name}}</small>
                                <small class="flex-fill text-center border-end py-2"><i class="fa fa-clock text-primary me-2"></i>{{ course.course_hours}} Hrs</small>
                                <small class="flex-fill text-center py-2"><i class="fa fa-user text-primary me-2"></i>{{ course.students_numbe}} Students</small>
                            </div>
                        </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% if courses.has_other_pages %}
        <div class="containerpagin">
            <ul class="pagination">
                
                {% if  courses.has_previous %}
                <li class="icon">
                    <a href="?page={{courses.previouse_page_number}}"><span class="fas fa-angle-left"></span>Previous</a>
                </li>
                {% endif %}

                {% for pg in courses.paginator.page_range %}
                <li><a href="?page={{pg}}">{{pg}}</a></li>
                {% endfor %}

                {% if courses.has_next %}
                <li class="icon">
                    <a href="?page={{courses.next_page_number}}">Next<span class="fas fa-angle-right"></span></a>
                </li>
                {% endif %}

            </ul>
        </div>
    {% endif %}
{% endblock %}

FCA_DJANGO/courses/templates/enroll_page.html
{% extends "base.html" %}
{% load static %}
{% block body %}
  <!-- Navbar Start -->
  <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
    <a href="/" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
        <h2 class="m-0 text-secondary"><img src="{% static 'img/logo.png'%}" alt="FCA" style="width:50px;">&nbsp;</i>French Canadian Academy </h2>
    </a>
    <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto p-4 p-lg-0">
            <a href="/" class="nav-item nav-link">Home</a>
            <a href="/about/" class="nav-item nav-link">About</a>
            <a href="/courses/" class="nav-item nav-link active">Courses</a>
            {% comment %} <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                <div class="dropdown-menu fade-down m-0">
                    <a href="team.html" class="dropdown-item">Our Team</a>
                    <a href="testimonial.html" class="dropdown-item">Testimonial</a>
                    <a href="404.html" class="dropdown-item">404 Page</a>
                </div>
            </div> {% endcomment %}
            <a href="/contact/" class="nav-item nav-link">Contact</a>
            <a href="/certificate/" class="nav-item nav-link">Certificate</a>
        </div>
        {% comment %} <a href="" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block">Join Now<i class="fa fa-arrow-right ms-3"></i></a> {% endcomment %}
    </div>
</nav>
<!-- Navbar End -->
    <!-- Contact Start  -->
    <div class="container-xxl py-5 ">
        <div class="container">
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="section-title bg-white text-center text-primary px-3">Enroll</h6>
                <h1 class="mb-5">Enroll to {{course.title}}</h1>
            </div>
            <div class="col-lg-12 col-md-12 wow fadeInUp" data-wow-delay="0.5s">
                <form role="form" method = "POST" enctype = "multipart/form-data">
                    {% csrf_token %}
                        <div class="col-12">
                            {{form}}
                        </div>
                        <div class="col-12">
                            <button class="btn btn-primary w-100 py-3 mt-3" type="submit">Enroll Now</button>
                        </div>
                    </div>
                </form>
            </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->
{% endblock %}

FCA_DJANGO/courses/templates/succ.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <!-- Navbar Start -->
<nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
    <a href="/" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
        <h2 class="m-0 text-secondary"><img src="{% static 'img/logo.png'%}" alt="FCA" style="width:50px;">&nbsp;</i>French Canadian Academy </h2>
    </a>
    <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto p-4 p-lg-0">
            <a href="/" class="nav-item nav-link">Home</a>
            <a href="/about/" class="nav-item nav-link">About</a>
            <a href="/courses/" class="nav-item nav-link">Courses</a>
            {% comment %} <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                <div class="dropdown-menu fade-down m-0">
                    <a href="team.html" class="dropdown-item">Our Team</a>
                    <a href="testimonial.html" class="dropdown-item">Testimonial</a>
                    <a href="404.html" class="dropdown-item">404 Page</a>
                </div>
            </div> {% endcomment %}
            <a href="/contact/" class="nav-item nav-link active">Contact</a>
            <a href="/certificate/" class="nav-item nav-link">Certificate</a>
        </div>
        {% comment %} <a href="" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block">Join Now<i class="fa fa-arrow-right ms-3"></i></a> {% endcomment %}
    </div>
</nav>
<!-- Navbar End -->

    <!-- About Start -->
    <div class="container mt-5 mbp-20">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h6 class="section-title bg-white text-center text-primary px-3">Welcome</h6>
            <div class="row g-4 justify-content-center">
                <div class="col-lg-6 text-center wow fadeInUp" data-wow-delay="0.3s">
                    <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                    <div class="row g-4 justify-content-center">
                    <h1 class="mb-4">You Are Enrolled Successfully <br> Wait For The Confirmation Call</h1>
                    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>.
                    </div>  
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->
{% endblock %}